### ISSUE TITLE
Report all errors not only the first one

### ISSUE THREAD

**Issue by stephanenicolas** [groupon/dependency-injection-checks#3]
It would make it more interesting to report all possible errors rather than only the first one, so a dev can fix them all in one shot.

Not sure about this issue, was the bug on my side ?

**Comment by code-twister** [comment]
@stephanenicolas this is the intended behaviour from day one. It should report all errors, can you give me an example when it doesn't? If not, let me know to close this issue.

**Comment by stephanenicolas** [comment]
I close as I don't remember the details. I'll reopen if I see it again.
