### ISSUE TITLE
add support for using annotationProcessor instead of apt

### ISSUE THREAD

**Issue by aegis123** [groupon/dependency-injection-checks#5]
as of the Android Gradle plugin 2.2 annotationProcessor is final and should be used instead of apt.

**Comment by code-twister** [comment]
Thanks for the info, I will look into this.

**Comment by Egorand** [comment]
Furthermore, AGP 3.0 actually breaks apt

**Comment by code-twister** [comment]
should work now in 1.0.2, let me know if this is still an issue for you

**Comment by Rainer-Lang** [comment]
@code-twister Have you changed the readme?
