### ISSUE TITLE
make sure dependencies are compileOnly

### ISSUE THREAD

**Issue by aegis123** [groupon/dependency-injection-checks#6]
Is it possible to make the dependencies of the processor compile only? When adding this to a project now it will add additional dependencies to you final apk that we not necessary for running the app.

now I have to add `includeCompileClasspath = true` to the `annotationProcessorOptions` because it wants to add auto-service to the compilepath which is not supported since 3.0.0

**Comment by code-twister** [comment]
Dependencies of the processor should be compile only. I'll take a look at this issue.

**Comment by stephanenicolas** [comment]
@aegis123 can you elaborate more on where you add `includeCompileClasspath = true` and what it means and does ? 
You mean auto-service 3.0.0 detects it is added to the classpath ? I really didn't get this part.

**Comment by aegis123** [comment]
@stephanenicolas I just followed the instructions the console gave in Android studio.

**Comment by aegis123** [comment]
hmm seems the issue is gone now could be because I updated from beta 2 to beta 3 in the mean time.

**Comment by code-twister** [comment]
changed dependencies to be compileOnly (seems a better approach anyway)
available in 1.0.2 on maven (bagdes take some time to update)
