### ISSUE TITLE
Wrong supported version

### ISSUE THREAD

**Issue by stephanenicolas** [groupon/dependency-injection-checks#7]
to get rid of this build message
```bash
warning: Supported source version 'RELEASE_7' from annotation processor 'com.groupon.android.dichecks.processor.DiChecksProcessor' less than -source '1.8'
```
replace 
https://github.com/groupon/dependency-injection-checks/blob/e7a4103d27f66a28f33bca1d8cfb84f7d2676bd7/compiler/src/main/java/com/groupon/android/dichecks/processor/DiChecksProcessor.java#L59

by `javax.lang.model.SourceVersion.latest()`. You can't use the annotation anymore to define the version then, you will have to override the equivalent method.

Please re-release when you could do it. Thx !

**Comment by code-twister** [comment]
fixed in 1.0.2 available on maven (bagdes take some time to update)
